과제1 --> 인자변환 함수로
과제2 --> DB로 넣어오기(SQLite)

SQLite로 넘기기

In [1]:
import requests

In [29]:
import urllib

In [30]:
def getData(numOfRows=10, pageNo=1, startPage=1, stationName="종로구", dataTerm="DAILY", ver=1.3):
    url = "http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty"
    params = {
        "serviceKey":"EdYKWkchoSlAG7pBW2tKSQJxp4G56PVOXaHvCJOlhtBQh7Y8ArTs7xZFAXJ81owZTEqFqiEtjn9hA6fDw%2B7D%2Bw%3D%3D",
        "numOfRows":numOfRows,
        "pageNo":pageNo,
        "startPage":startPage,
        "stationName":stationName,
        "dataTerm":dataTerm,
        "ver":ver
    }
    params["serviceKey"] = urllib.parse.unquote(params["serviceKey"])
    data = requests.get(url,params)
    return data

In [33]:
from bs4 import BeautifulSoup

In [34]:
data2 = BeautifulSoup(getData(stationName="성북구").text, "lxml")

In [35]:
data2

<?xml version="1.0" encoding="UTF-8"?><html><body><response>
<header>
<resultcode>00</resultcode>
<resultmsg>NORMAL SERVICE.</resultmsg>
</header>
<items>
<item>
<datatime>2018-07-17 21:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.003</so2value>
<covalue>0.3</covalue>
<o3value>0.007</o3value>
<no2value>0.019</no2value>
<pm10value>27</pm10value>
<pm10value24>35</pm10value24>
<pm25value>24</pm25value>
<pm25value24>25</pm25value24>
<khaivalue>74</khaivalue>
<khaigrade>2</khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>1</o3grade>
<no2grade>1</no2grade>
<pm10grade>2</pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h>1</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 20:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.003</so2value>
<covalue>0.3</covalue>
<o3value>0.014</o3value>
<no2value>0.016</no2value>
<pm10value>22</pm10value>
<pm10value24>38</pm10value24>
<pm25value>21</pm25value>
<pm25value24>25</pm25value24>
<khaivalue>74</khaivalue>
<khaigrade>2</khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>1</o3grade>
<no2grade>1</no2grade>
<pm10grade>2</pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h>1</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 19:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.002</so2value>
<covalue>0.3</covalue>
<o3value>0.021</o3value>
<no2value>0.012</no2value>
<pm10value>26</pm10value>
<pm10value24>45</pm10value24>
<pm25value>20</pm25value>
<pm25value24>26</pm25value24>
<khaivalue>77</khaivalue>
<khaigrade>2</khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>1</o3grade>
<no2grade>1</no2grade>
<pm10grade>2</pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h>1</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 18:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.003</so2value>
<covalue>0.3</covalue>
<o3value>0.024</o3value>
<no2value>0.011</no2value>
<pm10value>32</pm10value>
<pm10value24>51</pm10value24>
<pm25value>28</pm25value>
<pm25value24>26</pm25value24>
<khaivalue>77</khaivalue>
<khaigrade>2</khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>1</o3grade>
<no2grade>1</no2grade>
<pm10grade>2</pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h>2</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 17:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.004</so2value>
<covalue>0.3</covalue>
<o3value>0.022</o3value>
<no2value>0.014</no2value>
<pm10value>49</pm10value>
<pm10value24>-</pm10value24>
<pm25value>30</pm25value>
<pm25value24>26</pm25value24>
<khaivalue>-</khaivalue>
<khaigrade></khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>1</o3grade>
<no2grade>1</no2grade>
<pm10grade></pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h>2</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 16:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.005</so2value>
<covalue>0.3</covalue>
<o3value>0.025</o3value>
<no2value>0.019</no2value>
<pm10value>68</pm10value>
<pm10value24>-</pm10value24>
<pm25value>33</pm25value>
<pm25value24>25</pm25value24>
<khaivalue>-</khaivalue>
<khaigrade></khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>1</o3grade>
<no2grade>1</no2grade>
<pm10grade></pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h>2</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 15:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.006</so2value>
<covalue>0.3</covalue>
<o3value>0.033</o3value>
<no2value>0.017</no2value>
<pm10value>65</pm10value>
<pm10value24>-</pm10value24>
<pm25value>31</pm25value>
<pm25value24>-</pm25value24>
<khaivalue>-</khaivalue>
<khaigrade></khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>2</o3grade>
<no2grade>1</no2grade>
<pm10grade></pm10grade>
<pm25grade></pm25grade>
<pm10grade1h>2</pm10grade1h>
<pm25grade1h>2</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 14:00</datatime>
<mangname>도시대기</mangname>
<so2value>0.006</so2value>
<covalue>0.4</covalue>
<o3value>0.047</o3value>
<no2value>0.019</no2value>
<pm10value>65</pm10value>
<pm10value24>-</pm10value24>
<pm25value>38</pm25value>
<pm25value24>-</pm25value24>
<khaivalue>-</khaivalue>
<khaigrade></khaigrade>
<so2grade>1</so2grade>
<cograde>1</cograde>
<o3grade>2</o3grade>
<no2grade>1</no2grade>
<pm10grade></pm10grade>
<pm25grade></pm25grade>
<pm10grade1h>2</pm10grade1h>
<pm25grade1h>3</pm25grade1h>
</item>
<item>
<datatime>2018-07-17 13:00</datatime>
<mangname>도시대기</mangname>
<so2value>-</so2value>
<covalue>-</covalue>
<o3value>-</o3value>
<no2value>-</no2value>
<pm10value>-</pm10value>
<pm10value24>-</pm10value24>
<pm25value>-</pm25value>
<pm25value24>-</pm25value24>
<khaivalue>-</khaivalue>
<khaigrade></khaigrade>
<so2grade></so2grade>
<cograde></cograde>
<o3grade></o3grade>
<no2grade></no2grade>
<pm10grade></pm10grade>
<pm25grade></pm25grade>
<pm10grade1h></pm10grade1h>
<pm25grade1h></pm25grade1h>
</item>
<item>
<datatime>2018-07-17 12:00</datatime>
<mangname>도시대기</mangname>
<so2value>-</so2value>
<covalue>-</covalue>
<o3value>-</o3value>
<no2value>-</no2value>
<pm10value>-</pm10value>
<pm10value24>-</pm10value24>
<pm25value>-</pm25value>
<pm25value24>20</pm25value24>
<khaivalue>-</khaivalue>
<khaigrade></khaigrade>
<so2grade></so2grade>
<cograde></cograde>
<o3grade></o3grade>
<no2grade></no2grade>
<pm10grade></pm10grade>
<pm25grade>2</pm25grade>
<pm10grade1h></pm10grade1h>
<pm25grade1h></pm25grade1h>
</item>
</items>
<numofrows>10</numofrows>
<pageno>1</pageno>
<totalcount>23</totalcount>
</response>
</body></html>

In [36]:
import sqlite3

In [38]:
conn = sqlite3.connect("homework0717_hanhol.db")

In [39]:
cur = conn.cursor()

In [ ]:
children = item.children
childList = list()
for child in children:
    if child == '\n':
        continue;
    else:
        childList.append(child)

In [121]:
sql = "CREATE TABLE AIR("

for child in range(len(childList)):
    if child == (len(childList)-1):
        sql+=childList[child].name+")"
    else:
        sql+=childList[child].name+", "
print(sql)

CREATE TABLE AIR(datatime, mangname, so2value, covalue, o3value, no2value, pm10value, pm10value24, pm25value, pm25value24, khaivalue, khaigrade, so2grade, cograde, o3grade, no2grade, pm10grade, pm25grade, pm10grade1h, pm25grade1h)

In [122]:
cur.execute(sql)

In [123]:
dataList = data2.findAll("item")

In [149]:
temp = tuple(i.text for i in dataList[0] if i != '\n')

In [154]:
for data in range(len(dataList)):
    temp = tuple(i.text for i in dataList[data] if i != '\n')
    cur.execute("INSERT INTO AIR VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", temp)

In [155]:
result = cur.execute("select * from air")

In [158]:
result.fetchall()

[('2018-07-17 21:00',
  '도시대기',
  '0.003',
  '0.3',
  '0.007',
  '0.019',
  '27',
  '35',
  '24',
  '25',
  '74',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '2',
  '1',
  '2'),
 ('2018-07-17 20:00',
  '도시대기',
  '0.003',
  '0.3',
  '0.014',
  '0.016',
  '22',
  '38',
  '21',
  '25',
  '74',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '2',
  '1',
  '2'),
 ('2018-07-17 19:00',
  '도시대기',
  '0.002',
  '0.3',
  '0.021',
  '0.012',
  '26',
  '45',
  '20',
  '26',
  '77',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '2',
  '1',
  '2'),
 ('2018-07-17 18:00',
  '도시대기',
  '0.003',
  '0.3',
  '0.024',
  '0.011',
  '32',
  '51',
  '28',
  '26',
  '77',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '2',
  '2',
  '2'),
 ('2018-07-17 17:00',
  '도시대기',
  '0.004',
  '0.3',
  '0.022',
  '0.014',
  '49',
  '-',
  '30',
  '26',
  '-',
  '',
  '1',
  '1',
  '1',
  '1',
  '',
  '2',
  '2',
  '2'),
 ('2018-07-17 16:00',
  '도시대기',
  '0.005',
  '0.3',
  '0.025',
  '0.019',
  '68',
  '-',
  '33',
  '25',
  '-',
  '',
  '1',
  '1',
  '1',
  '1',
  '',
  '2',
  '2',
  '2'),
 ('2018-07-17 15:00',
  '도시대기',
  '0.006',
  '0.3',
  '0.033',
  '0.017',
  '65',
  '-',
  '31',
  '-',
  '-',
  '',
  '1',
  '1',
  '2',
  '1',
  '',
  '',
  '2',
  '2'),
 ('2018-07-17 14:00',
  '도시대기',
  '0.006',
  '0.4',
  '0.047',
  '0.019',
  '65',
  '-',
  '38',
  '-',
  '-',
  '',
  '1',
  '1',
  '2',
  '1',
  '',
  '',
  '2',
  '3'),
 ('2018-07-17 13:00',
  '도시대기',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''),
 ('2018-07-17 12:00',
  '도시대기',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-',
  '20',
  '-',
  '',
  '',
  '',
  '',
  '',
  '',
  '2',
  '',
  '')]